version: "3.5"
services:
  api_eureka:
    container_name: api_eureka
    image: docker.privjaac.com/pragma/co-com-pragma-api-eureka:latest
    restart: always
    build:
      context: .
    ports:
      - "91:91"
    networks:
      - net_jaac
networks:
  net_jaac:
    name: net_jaac
    driver: bridge